config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      get 'topic/:topic_id', to: 'topic#show'
    end
  end

  root to: 'home#index'

  get '/callback', to: 'events#callback', as: 'callback'

  get '/control-panel', to: 'control_panel#index', as: 'control_panel'
  get '/control-panel/:page', to: 'control_panel#index'
  put '/control-panel/:page', to: 'control_panel#new'
  post '/control-panel', to: 'control_panel#update', as: 'control_panel_update'

  get '/control-panel/calendars/sync', to: 'control_panel#sync_calendars'
  delete '/control-panel/calendars/delete', to: 'control_panel#delete_calendar', as: 'delete_calendar'

  get '/user/settings', to: 'user_settings#show', as: 'user_settings'

  get '/calendar', to: 'events#index', as: 'calendar'
  post '/calendar', to: 'events#create'

  post '/users/sign_out', to: 'devise/sessions#destroy', as: 'log_out'
  post '/user', to: 'user_settings#update', as: 'update_user'

  get '/learning-trails', to: 'learning_trails#index', as: 'learning_trails'
  get '/learning-trails/:id', to: 'learning_trails#show', constraints: { id: /[0-9]+(\%7C[0-9]+)*/ }
  get '/learning-trails/:name', to: 'learning_trails#show'

  post '/learning-trails/add', to: 'learning_trails#add', as: 'add_topic'
  post '/learning-trails/complete-task', to: 'learning_trails#complete_task', as: 'complete_task'
  post '/learning-trails/reset-task', to: 'learning_trails#reset_task', as: 'reset_task'
  post '/learning-trails/complete-goal', to: 'learning_trails#complete_task', as: 'complete_goal'
  post '/learning-trails/reset-goal', to: 'learning_trails#reset_task', as: 'reset_goal'

  get '/api/events', to: 'event_api#index'
end

app/views/shared/_cdn_stylesheets.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/css/tether.min.css" /> 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

app/views/shared/_flash.html.erb
<div class="row">
  <% if notice %>
    <div class="alert alert-success col-md-6 offset-md-3 margin-top-10 alert-dismissible fade show" role="alert">
      <span class="flash-text"><%= notice %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger col-md-6 offset-md-3 margin-top-10 alert-dismissible fade show" role="alert">
      <span class="flash-text"><%= alert %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar">
    <div class="container">
      <div class="row footer-row">
        <div class="col-md-4 footer-columns">
          <a href="http://8thlight.com">
            An 8th Light project
          </a>
        </div>
        <div class="col-md-4 footer-columns">
          <span>© 2017 8th Light, Inc.</span>
        </div>
        <div class="col-md-4 footer-columns">
          <span>Live, learn, code</span>
        </div>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-toggleable-md">
  <a class="navbar-brand" href=<%= root_path %>>
    Zagaku
  </a>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarContent"
          aria-controls="navbarContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="fa fa-bars"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="<%= root_path %>" class="nav-link nav-link-color">
          <i class="fa fa-home"></i>
          Home
        </a>
      </li>
      <% if user_signed_in? && current_user[:employee] %>
        <a href="<%= calendar_path %>" class="nav-link nav-link-color">
          <i class="fa fa-clock-o"></i>
          Schedule
        </a>
      <% end %>
      <li class="nav-item">
        <a href="<%= learning_trails_path %>" class="nav-link nav-link-color">
          <i class="fa fa-map-signs"></i>
          Learning Trails
        </a>
      </li>
    </ul>
    <ul class="navbar-nav right">

    </ul>
    <% if user_signed_in? %>

      <div class="dropdown">
        <button class="z-button dropdown-toggle nav-dropdown-button"
                type="button"
                id="navUserMenu"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
          <%= current_user.email %>
        </button>
        <div class="dropdown-menu" aria-labelledby="navUserMenu">
          <% if user_signed_in? && current_user[:employee] %>
              <a href="<%= control_panel_path %>" data-method="get" class="dropdown-item">
                <i class="fa fa-cog"></i>
                Control Panel
              </a>
          <% end %>

          <a href="<%= user_settings_path %>" data-method="get" class="dropdown-item">
            <i class="fa fa-bars"></i>
            User Settings
          </a>

          <a href="<%= log_out_path %>" data-method="post" class="dropdown-item">
            <i class="fa fa-sign-out"></i>
            Sign Out
          </a>
        </div>
      </div>
    <% end %>
  </div>
</nav>