config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      get 'topic/:topic_id', to: 'topic#show'
    end
  end

  root to: 'home#index'

  get '/callback', to: 'events#callback', as: 'callback'

  get '/control-panel', to: 'control_panel#index', as: 'control_panel'
  get '/control-panel/:page', to: 'control_panel#index'
  put '/control-panel/:page', to: 'control_panel#new'
  post '/control-panel', to: 'control_panel#update', as: 'control_panel_update'

  get '/control-panel/calendars/sync', to: 'control_panel#sync_calendars'
  delete '/control-panel/calendars/delete', to: 'control_panel#delete_calendar', as: 'delete_calendar'

  get '/user/settings', to: 'user_settings#show', as: 'user_settings'

  get '/calendar', to: 'events#index', as: 'calendar'
  post '/calendar', to: 'events#create'

  post '/users/sign_out', to: 'devise/sessions#destroy', as: 'log_out'
  post '/user', to: 'user_settings#update', as: 'update_user'

  get '/learning-trails', to: 'learning_trails#index', as: 'learning_trails'
  get '/learning-trails/:id', to: 'learning_trails#show', constraints: { id: /[0-9]+(\%7C[0-9]+)*/ }
  get '/learning-trails/:name', to: 'learning_trails#show'

  post '/learning-trails/add', to: 'learning_trails#add', as: 'add_topic'
  post '/learning-trails/complete-task', to: 'learning_trails#complete_task', as: 'complete_task'
  post '/learning-trails/reset-task', to: 'learning_trails#reset_task', as: 'reset_task'
  post '/learning-trails/complete-goal', to: 'learning_trails#complete_task', as: 'complete_goal'
  post '/learning-trails/reset-goal', to: 'learning_trails#reset_task', as: 'reset_goal'

  get '/api/events', to: 'event_api#index'
end

app/controllers/control_panel_controller.rb
include ControlPanelHelper

class ControlPanelController < ApplicationController
  before_action :require_employee

  def index
    @users = User.all
    @panels = %w[authorization calendars]
    @calendars = Calendar.all
    @page = cp_params[:page] unless cp_params[:page].nil?
    @cp_action = cp_params[:cp_action] unless cp_params[:cp_action].nil?
  end

  def update
    @page = 'authorization'
    result = User.find(cp_params[:user_id].to_i)
                 .update(employee: cp_params[:employee] == 'true')
    if result
      flash[:notice] = 'User permissions updated.'
    else
      flash[:danger] = 'User permissions could not be created.'
    end
    redirect_to '/control-panel/authorization'
  end

  def new
    ical_link_valid = ControlPanelHelper
                      .valid_ical_link(cp_params[:google_ical_link])
    name_valid = !Calendar.all
                          .pluck(:name)
                          .include?(cp_params[:calendar_name])
    if ical_link_valid && name_valid
      create_calendar
      flash[:notice] = 'Calendar created successfully'
      redirect_to '/control-panel/calendars'
    else
      flash[:alert] = 'Calendar name taken' unless name_valid
      flash[:alert] = 'Invalid iCal link' unless ical_link_valid
      redirect_to '/control-panel/calendars?cp_action=add'
    end
  end

  def sync_calendars
    EventJob.perform_now
    flash[:notice] = 'Calendar sync complete'
    redirect_to '/control-panel/calendars'
  end

  def delete_calendar
    calendar = Calendar.find(cp_params[:calendar_id])
    calendar.events.delete_all
    result = calendar.delete
    if result
      flash[:notice] = "The calendar was deleted successfully"
    else
      flash[:alert] = "The calendar could not be deleted"
    end
    @page = 'calendars'
    redirect_to '/control-panel/calendars'
  end

  private

  def create_calendar
    cal = Calendar.new
    cal.name = cp_params[:calendar_name]
    cal.google_ical_link = cp_params[:google_ical_link]
    cal.time_zone = cp_params[:calendar][:time_zone]
    cal.save
  end

  def cp_params
    params.permit(:user_id,
                  :employee,
                  :utf8,
                  :authenticity_token,
                  :commit,
                  :page,
                  :cp_action,
                  :calendar_name,
                  :calendar_id,
                  :google_ical_link,
                  :_method,
                  calendar: {})
  end

  def require_employee
    redirect_to root_path unless current_user && current_user[:employee]
  end
end

app/helpers/control_panel_helper.rb
module ControlPanelHelper

  def valid_ical_link(link)
    begin
      calendar_file = open(link, &:read)
      Icalendar::Calendar.parse(calendar_file).length > 0
    rescue
      false
    end
  end
end

app/views/control_panel/_authorization.html.erb
<h4 class="topic-page-summary">Authorization</h4>
<br/>
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3">
      <p>
        <strong><%= "#{user.first_name.titlecase} #{user.last_name.titlecase}" %></strong><br/>
        <%= "#{user.email}" %>
      </p>
      <%= form_tag("/control-panel", method: "post") do %>
        <%= hidden_field_tag 'user_id', user.id %>
        <%= label_tag 'Employee level access' %>
        <%= check_box_tag 'employee', 'true', user.employee %><br/>
        <%= submit_tag 'save', class: "z-button inline" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/control_panel/_calendars.html.erb
<h4 class="topic-page-summary">Calendars</h4>
<br/>

<% if @cp_action != 'add' %>
  <div class="row">
    <div class="col-md-1">
      <%= form_tag '/control-panel', method: 'get' do %>
        <%= hidden_field_tag :cp_action, 'add' %>
        <%= hidden_field_tag :page, 'calendars' %>
        <%= submit_tag "Add Calendar", class: "control-panel-tab control-panel-inactive" %>
      <% end %>
    </div>
    <div class="col-md-1">
      <%= form_tag '/control-panel/calendars/sync', method: 'get' do %>
        <%= hidden_field_tag :page, 'calendars' %>
        <%= submit_tag "Sync Calendars", class: "control-panel-tab control-panel-inactive" %>
      <% end %>
    </div>
  </div>


  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Time Zone</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      <% @calendars.each do |calendar| %>
        <tr>
          <td><%= calendar.name %></td>
          <td><%= calendar.time_zone %></td>
          <td>
            <button class="z-button"
                    type="button"
                    data-toggle="modal"
                    data-target="#delete-calendar-modal-<%= calendar.id %>">
              Delete Calendar
            </button>

            <div class="modal fade delete-calendar-modal"
                 id="delete-calendar-modal-<%= calendar.id %>"
                 tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content calendar-modal">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Deleting this calendar will remove the calendar and all associated events.
                  </div>
                  <div class="modal-footer">
                    <%= form_tag(delete_calendar_path, method: "delete") do %>
                      <input type="hidden"
                             id="calendar_id"
                             name="calendar_id"
                             value="<%= calendar.id %>" />
                      <button type="button" class="z-button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">Cancel</span>
                      </button>
                      <%= submit_tag("Delete Calendar", class: "btn-danger z-button") %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


<% end %>

<% if @cp_action == 'add' %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h4 class="topic-page-summary">Add new calendar</h4>
        <p><i>Due to the sensitivity of company calendars, we use private iCal links to integrate calendars.</i></p>
        <%= form_tag '/control-panel/calendars', method: 'put'  do %>
          <%= label_tag :name, "Calendar Name", class: 'control-panel-form-label' %>
          <%= text_field_tag :calendar_name, nil, class: 'form-control' %>
          <br/>

          <%= label_tag :google_ical_link, "Google Private iCal Link", class: 'control-panel-form-label' %>
          <%= text_field_tag :google_ical_link, nil, class: 'form-control' %>
          <br/>

          <%= label_tag 'calendar[time_zone]', "Time Zone", class: 'control-panel-form-label' %>
          <%= select "calendar",
                     "time_zone",
                     ActiveSupport::TimeZone.all,
                     { include_blank: false },
                     { class: 'form-control'} %>
          <br/>

          <%= submit_tag "Create Calendar", class: "control-panel-tab control-panel-inactive" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/control_panel/index.html.erb
<div class="container-fluid page-textbox">
  <h3 class="topic-page-summary">Control Panel</h3>
  <div class="row">
    <% @panels.each do |panel| %>
      <form action="<%= "/control-panel/#{panel}"%>">
        <input class="<%= "control-panel-tab control-panel-#{@page == panel ? 'active' : 'inactive'}"%>"
               type="submit"
               value=<%= panel.titlecase %> />
      </form>
    <% end %>
  </div>
  <br/>

  <% if @page == 'authorization' %>
    <%= render partial: 'control_panel/authorization' %>
  <% end %>

  <% if @page == 'calendars' %>
    <%= render partial: 'control_panel/calendars' %>
  <% end %>

  <% if @page == 'alerts' %>
    <%= render partial: 'control_panel/alerts' %>
  <% end %>
</div>